# Generated by Django 3.2.13 on 2022-04-25 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_booking_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.inventory'),
        ),
    ]
