# Generated by Django 3.2.13 on 2022-04-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_alter_booking_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='remain_tickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
